-------------------------------------------------------------------------------
--  EUI_Voidlol_SharedMedia.lua
--  Registers Media/Fonts and Media/Sounds with LibSharedMedia-3.0 (embedded by
--  EllesmereUI, a hard dependency, so it is already loaded by the time this
--  file runs) so every SharedMedia-aware dropdown can use them regardless of
--  whether ElvUI or M33kAuras (their original sources) are installed.
-------------------------------------------------------------------------------
local ADDON_NAME = ...

local LSM = LibStub and LibStub("LibSharedMedia-3.0", true)
if not LSM then return end

local MEDIA_PATH = "Interface\\AddOns\\" .. ADDON_NAME .. "\\Media\\"

local FONTS = {
    { name = "ActionMan", file = "ActionMan.ttf" },
    { name = "ContinuumMedium", file = "ContinuumMedium.ttf" },
    { name = "DieDieDie", file = "DieDieDie.ttf" },
    { name = "Expressway", file = "Expressway.ttf" },
    { name = "FiraMono-Medium", file = "FiraMono-Medium.ttf" },
    { name = "FiraSans-Heavy", file = "FiraSans-Heavy.ttf" },
    { name = "FiraSans-Medium", file = "FiraSans-Medium.ttf" },
    { name = "FiraSansCondensed-Heavy", file = "FiraSansCondensed-Heavy.ttf" },
    { name = "FiraSansCondensed-Medium", file = "FiraSansCondensed-Medium.ttf" },
    { name = "Homespun", file = "Homespun.ttf" },
    { name = "Invisible", file = "Invisible.ttf" },
    { name = "PTSansNarrow-Bold", file = "PTSansNarrow-Bold.ttf" },
    { name = "PTSansNarrow-Regular", file = "PTSansNarrow-Regular.ttf" },
    { name = "PTSansNarrow", file = "PTSansNarrow.ttf" },
}
for _, f in ipairs(FONTS) do
    LSM:Register(LSM.MediaType.FONT, f.name, MEDIA_PATH .. "Fonts\\" .. f.file)
end

local SOUNDS = {
    { name = "AcousticGuitar", file = "AcousticGuitar.ogg" },
    { name = "Adds", file = "Adds.ogg" },
    { name = "aggro", file = "aggro.ogg" },
    { name = "AirHorn", file = "AirHorn.ogg" },
    { name = "Applause", file = "Applause.ogg" },
    { name = "Arrow_Swoosh", file = "Arrow_Swoosh.ogg" },
    { name = "AwwCrap", file = "AwwCrap.ogg" },
    { name = "bam", file = "bam.ogg" },
    { name = "BananaPeelSlip", file = "BananaPeelSlip.ogg" },
    { name = "BatmanPunch", file = "BatmanPunch.ogg" },
    { name = "BbqAss", file = "BbqAss.ogg" },
    { name = "bear_polar", file = "bear_polar.ogg" },
    { name = "bigkiss", file = "bigkiss.ogg" },
    { name = "BikeHorn", file = "BikeHorn.ogg" },
    { name = "BITE", file = "BITE.ogg" },
    { name = "Blast", file = "Blast.ogg" },
    { name = "Bleat", file = "Bleat.ogg" },
    { name = "Boss", file = "Boss.ogg" },
    { name = "BoxingArenaSound", file = "BoxingArenaSound.ogg" },
    { name = "Brass", file = "Brass.mp3" },
    { name = "burp4", file = "burp4.ogg" },
    { name = "CartoonVoiceBaritone", file = "CartoonVoiceBaritone.ogg" },
    { name = "CartoonWalking", file = "CartoonWalking.ogg" },
    { name = "cat2", file = "cat2.ogg" },
    { name = "CatMeow2", file = "CatMeow2.ogg" },
    { name = "chant2", file = "chant2.ogg" },
    { name = "chant4", file = "chant4.ogg" },
    { name = "ChickenAlarm", file = "ChickenAlarm.ogg" },
    { name = "chimes", file = "chimes.ogg" },
    { name = "Circle", file = "Circle.ogg" },
    { name = "cookie", file = "cookie.ogg" },
    { name = "CowMooing", file = "CowMooing.ogg" },
    { name = "Cross", file = "Cross.ogg" },
    { name = "Diamond", file = "Diamond.ogg" },
    { name = "DontRelease", file = "DontRelease.ogg" },
    { name = "DoubleWhoosh", file = "DoubleWhoosh.ogg" },
    { name = "Drums", file = "Drums.ogg" },
    { name = "DumbShit", file = "DumbShit.ogg" },
    { name = "Empowered", file = "Empowered.ogg" },
    { name = "ErrorBeep", file = "ErrorBeep.ogg" },
    { name = "ESPARK1", file = "ESPARK1.ogg" },
    { name = "Fireball", file = "Fireball.ogg" },
    { name = "Focus", file = "Focus.ogg" },
    { name = "Gasp", file = "Gasp.ogg" },
    { name = "Glass", file = "Glass.mp3" },
    { name = "GoatBleating", file = "GoatBleating.ogg" },
    { name = "heartbeat", file = "heartbeat.ogg" },
    { name = "HeartbeatSingle", file = "HeartbeatSingle.ogg" },
    { name = "hic3", file = "hic3.ogg" },
    { name = "huh_1", file = "huh_1.ogg" },
    { name = "hurricane", file = "hurricane.ogg" },
    { name = "hyena", file = "hyena.ogg" },
    { name = "Idiot", file = "Idiot.ogg" },
    { name = "kaching", file = "kaching.ogg" },
    { name = "KittenMeow", file = "KittenMeow.ogg" },
    { name = "Left", file = "Left.ogg" },
    { name = "MamaWeekends", file = "MamaWeekends.ogg" },
    { name = "moan", file = "moan.ogg" },
    { name = "Moon", file = "Moon.ogg" },
    { name = "Next", file = "Next.ogg" },
    { name = "OhNo", file = "OhNo.ogg" },
    { name = "panther1", file = "panther1.ogg" },
    { name = "phone", file = "phone.ogg" },
    { name = "Portal", file = "Portal.ogg" },
    { name = "Protected", file = "Protected.ogg" },
    { name = "PUNCH", file = "PUNCH.ogg" },
    { name = "rainroof", file = "rainroof.ogg" },
    { name = "Release", file = "Release.ogg" },
    { name = "Right", file = "Right.ogg" },
    { name = "RingingPhone", file = "RingingPhone.ogg" },
    { name = "RoaringLion", file = "RoaringLion.ogg" },
    { name = "RobotBlip", file = "RobotBlip.ogg" },
    { name = "rocket", file = "rocket.ogg" },
    { name = "RoosterChickenCalls", file = "RoosterChickenCalls.ogg" },
    { name = "RunAway", file = "RunAway.ogg" },
    { name = "RunFast", file = "RunFast.ogg" },
    { name = "SharpPunch", file = "SharpPunch.ogg" },
    { name = "SheepBleat", file = "SheepBleat.ogg" },
    { name = "shipswhistle", file = "shipswhistle.ogg" },
    { name = "shot", file = "shot.ogg" },
    { name = "Shotgun", file = "Shotgun.ogg" },
    { name = "Skull", file = "Skull.ogg" },
    { name = "snakeatt", file = "snakeatt.ogg" },
    { name = "sneeze", file = "sneeze.ogg" },
    { name = "sonar", file = "sonar.ogg" },
    { name = "splash", file = "splash.ogg" },
    { name = "Spread", file = "Spread.ogg" },
    { name = "Square", file = "Square.ogg" },
    { name = "Squeakypig", file = "Squeakypig.ogg" },
    { name = "SqueakyToyShort", file = "SqueakyToyShort.ogg" },
    { name = "SquishFart", file = "SquishFart.ogg" },
    { name = "Stack", file = "Stack.ogg" },
    { name = "Star", file = "Star.ogg" },
    { name = "StopRunningSlimeBall", file = "StopRunningSlimeBall.ogg" },
    { name = "Switch", file = "Switch.ogg" },
    { name = "swordecho", file = "swordecho.ogg" },
    { name = "SynthChord", file = "SynthChord.ogg" },
    { name = "TadaFanfare", file = "TadaFanfare.ogg" },
    { name = "Taunt", file = "Taunt.ogg" },
    { name = "TempleBellHuge", file = "TempleBellHuge.ogg" },
    { name = "throwknife", file = "throwknife.ogg" },
    { name = "thunder", file = "thunder.ogg" },
    { name = "Torch", file = "Torch.ogg" },
    { name = "Triangle", file = "Triangle.ogg" },
    { name = "Warning", file = "Warning.ogg" },
    { name = "WarningSiren", file = "WarningSiren.ogg" },
    { name = "WaterDrop", file = "WaterDrop.ogg" },
    { name = "Whisper", file = "Whisper.ogg" },
    { name = "wickedmalelaugh1", file = "wickedmalelaugh1.ogg" },
    { name = "wilhelm", file = "wilhelm.ogg" },
    { name = "wlaugh", file = "wlaugh.ogg" },
    { name = "wolf5", file = "wolf5.ogg" },
    { name = "Xylophone", file = "Xylophone.ogg" },
    { name = "YankieBangBang", file = "YankieBangBang.ogg" },
    { name = "yeehaw", file = "yeehaw.ogg" },
}
for _, s in ipairs(SOUNDS) do
    LSM:Register(LSM.MediaType.SOUND, s.name, MEDIA_PATH .. "Sounds\\" .. s.file)
end
